server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 329893387589100
            client-secret: c8433775f2d257f7dea093957368c7cf
            scope: public_profile email user_location
          google:
            client-id: 566746547955-p61061irrafjgv1mh0lh77t0ss72tg1i.apps.googleusercontent.com
            client-secret: TIaTzstyZl8KZ6h35tiAVuHm
          crypto-portfolio:
            client-id: crypto-portfolio
            client-secret: e0bb45ee-70b2-4ad3-9d4e-b10c169c3a1b
            client-name: Crypto Portfolio
            scope: openid
            redirect-uri: http://localhost:8081/login/oauth2/code/crypto-portfolio
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: keycloak-provider
        provider:
            keycloak-provider:
              token-uri: http://localhost:8080/auth/realms/Cryptoinc/protocol/openid-connect/token
              authorization-uri: http://localhost:8080/auth/realms/Cryptoinc/protocol/openid-connect/auth
              user-info-uri: http://localhost:8080/auth/realms/Cryptoinc/protocol/openid-connect/userinfo
              jwk-set-uri: http://localhost:8080/auth/realms/Cryptoinc/protocol/openid-connect/certs
              user-name-attribute: name
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO