spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 254068796447369
            client-secret: 47e0400c3f46e29ff86560ad9de07f56
            scope: public_profile email
          google:
            client-id: 512911572062-hpvnlt3tiakmrblcor5jqr49e6tjrmfv.apps.googleusercontent.com
            client-secret: aL4sn408PAKr0Fq4igZyUERb
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO